### PR TITLE
chore(ens): replacing common::ens with the alloy_ens crate.

### LINKED ISSUE #10514: chore(`common`): deprecate `ens.rs`, replace with `alloy-ens`
### Component

Other (please describe)

### Describe the feature you would like

As indicated in https://github.com/foundry-rs/foundry/pull/10454#discussion_r2088705762 we no longer need this implementation as we can rely on `alloy-ens`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by l1nxy**
## Motivation
Close #10514 
As indicated in https://github.com/foundry-rs/foundry/pull/10454#discussion_r2088705762 we no longer need this implementation as we can rely on alloy-ens

## Solution
Using `alloy-ens` crate implementation.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/cast/src/cmd/logs.rs [hunk 1]
```diff
@@ -77,7 +77,7 @@ impl LogsArgs {
         if !subscribe {
             let logs = cast.filter_logs(filter).await?;
             sh_println!("{logs}")?;
-            return Ok(())
+            return Ok(());
```
Comment (zerosnacks) [inline crates/cast/src/cmd/logs.rs:80]: Please undo the semicolon insertions, see the contribution guide for clippy / fmt, we use a nightly version for them

**Review by zerosnacks — COMMENTED** [review]
Thanks! Lgtm, small note on unintended formatting changes

**Comment by zerosnacks** [comment]
> @zerosnacks Hi, the CI failed the no-features check, but the `resolve` call depends on the `provider` feature. What should I do?
> 
> > error[E0599]: no method named `resolve` found for enum `NameOrAddress` in the current scope
> > --> crates/cli/src/utils/abi.rs:14:61
> > |
> > 14 |             let addr = NameOrAddress::Name(arg.to_string()).resolve(provider).await;
> > |                                                             ^^^^^^^ method not found in `NameOrAddress`

this likely means you have to add `provider` here: https://github.com/foundry-rs/foundry/blob/64ee425eac73885d4928201026b98e690d205a62/crates/cli/Cargo.toml#L33

the crate check basically does a check on whether each crate can compile in isolation to make sure the correct feature flags are set in the crate itself

**Review by mattsse — APPROVED** [review]
cool, ty!

**Review by zerosnacks — APPROVED** [review]
Thanks!
