### ISSUE TITLE
bug(`forge bind`): generated contract bindings are incompatible with alloy-rs `0.14.0` + serde is not added as dependency

### ISSUE THREAD

**Issue by QYuQianchen** [foundry-rs/foundry#10321]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.1.0-nightly Commit SHA: f0e24fb6cfc9018d986d3136ab00aa5077994994 Build Timestamp: 2025-04-15T06:04:06.457241000Z (1744697046)

### What version of Foundryup are you on?

foundryup: 1.0.1

### What command(s) is the bug in?

forge bind

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running `forge bind` against `alloy` v0.14.0, the generated Rust code no longer compiles because the `forge bind` template still assumes pre‑0.14 interfaces in `alloy-contract` and `alloy-sol-types`.

The following errors pop up when using `alloy` crate of v0.14.0 with "transports" feature enabled:
1. Missing Transport
```
error[E0405]: cannot find trait Transport in module alloy_contract::private
     |
2925 |         T: alloy_contract::private::Transport + ::core::clone::Clone,
     |                                     ^^^^^^^^^ not found in alloy_contract::private
```

2. `abi_decode_returns` lost its `validate: bool` parameter
```
error[E0050]: method abi_decode_returns has 2 parameters but the declaration in trait abi_decode_returns has 1
     |
1119 |                   data: &[u8],
     |  _______________________^
1120 | |                 validate: bool,
     | |______________________________^ expected 1 parameter, found 2
     |
     = note: abi_decode_returns from trait: fn(&[u8]) -> std::result::Result<<Self as SolCall>::Return, alloy::alloy_sol_types::Error>
```

3. `decode_raw_log dropped` its `validate: bool` parameter as well
```
error[E0050]: method decode_raw_log has 3 parameters but the declaration in trait alloy::alloy_sol_types::SolEventInterface::decode_raw_log has 2
     |
2843 |               topics: &[alloy_sol_types::Word],
     |  _____________________^
2844 | |             data: &[u8],
2845 | |             validate: bool,
     | |__________________________^ expected 2 parameters, found 3
     |
     = note: decode_raw_log from trait: fn(&[alloy::alloy_primitives::FixedBytes<32>], &[u8]) -> std::result::Result<Self, alloy::alloy_sol_types::Error>
```

4. `SolCallBuilder` type alias lost a generic parameter
```
error[E0107]: type alias takes at most 3 generic arguments but 4 generic arguments were supplied
     |
3124 |         ) -> alloy_contract::SolCallBuilder<T, &P, bindKeysCall, N> {
     |                              ^^^^^^^^^^^^^^                    --- help: remove the unnecessary generic argument
     |                              |
     |                              expected at most 3 generic arguments
     |
note: type alias defined here, with at most 3 generic parameters: P, C, N
```

For the `validate` param, [the change log of `alloy-sol-macro-expander` (part of `alloy-core`)](https://github.com/alloy-rs/core/blob/ed6b0cc9d7b329d82b0502579122d807425fc27c/crates/sol-macro-expander/CHANGELOG.md) indicates that it has been removed in version "1.0.0" (released after version "0.8.24"), while [the version used in `foundry`](https://github.com/foundry-rs/foundry/blob/1da4d324652b3a61f7c7128a6d28f9d6239e8218/Cargo.toml#L235) stays at "0.8.22"

**Comment by zerosnacks** [comment]
No longer blocked after PR updating to Alloy 1.0 has landed

**Comment by QYuQianchen** [comment]
The generated still doesn't follow the change introduced in https://github.com/alloy-rs/core/pull/863
```
#[inline]
fn abi_decode_returns(
    data: &[u8],
    validate: bool,
) -> alloy_sol_types::Result<Self::Return> {
```

**Comment by zerosnacks** [comment]
> The generated still doesn't follow the change introduced in [alloy-rs/core#863](https://github.com/alloy-rs/core/pull/863)
> 
> ```
> #[inline]
> fn abi_decode_returns(
>     data: &[u8],
>     validate: bool,
> ) -> alloy_sol_types::Result<Self::Return> {
> ```

Would you mind expanding on the above?

The bindings generated using https://github.com/foundry-rs/foundry/pull/10563 generate

```rust
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(|r| {
                        let r: numberReturn = r.into();
                        r._0
                    })
            }
```

cc @yash-atreya

**Comment by QYuQianchen** [comment]
Sure. I think you could also try to reproduce:
```
$ forge --version
forge Version: 1.2.0-nightly
Commit SHA: dc6a2160ef1cecf21531eaf6722af9f7f64ca3c7
Build Timestamp: 2025-05-19T06:02:09.410437000Z (1747634529)
Build Profile: maxperf
```
At the root of https://github.com/hoprnet/hoprnet/tree/master, run
```
cd ethereum/contracts; \
    forge bind --offline --bindings-path ./../bindings/src/codegen \
      --module --alloy --overwrite \
      --force --skip-cargo-toml --alloy-version "1.0.4" \
      --select '^(HoprAnnouncements|HoprAnnouncementsEvents|HoprCapabilityPermissions|HoprChannels|HoprChannelsEvents|HoprCrypto|HoprDummyProxyForNetworkRegistry|HoprBoost|HoprToken|HoprLedger|HoprLedgerevents|HoprMultisig|HoprNetworkRegistry|HoprNetworkRegistryEvents|HoprNodeManagementModule|HoprNodeSafeRegistry|HoprNodeSafeRegistryEvents|HoprNodeStakeFactory|HoprNodeStakeFactoryEvents|HoprSafeProxyForNetworkRegistry|HoprStakingProxyForNetworkRegistry|HoprTicketPriceOracle|HoprTicketPriceOracleEvents|HoprWinningProbabilityOracle|HoprWinningProbabilityOracleEvents)$'
```

In any of the generated binding (i.e. under `./ethereum/bindings/src/codegen`), there is 
```
#[inline]
fn abi_decode_returns(
    data: &[u8],
    validate: bool,
) -> alloy_sol_types::Result<Self::Return> {
    <Self::ReturnTuple<
        '_,
    > as alloy_sol_types::SolType>::abi_decode_sequence(data, validate)
        .map(Into::into)
}
```

**Comment by zerosnacks** [comment]
@QYuQianchen would you updating w/ `foundryup -i nightly`? 

```
forge Version: 1.2.0-nightly
Commit SHA: 0ca8dd47ef6b28aaf2d61837954ca73d4a0b435e
Build Timestamp: 2025-05-20T06:02:05.187829426Z (1747720925)
Build Profile: maxperf
```

The build of the 19th does not yet include Alloy's 1.0 bump
