### ISSUE TITLE
forge build result in generic "Solc Error:"

### ISSUE THREAD

**Issue by StErMi** [foundry-rs/foundry#2712]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6cd6618 2022-08-11T00:05:44.416299Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon M1)

### Describe the bug

When I try to build and test the project, I get the following error

```bash
[⠊] Compiling...
[⠰] installing solc version "0.8.15"
[⠒] Successfully installed solc 0.8.15
Error: 
Solc Error: 
```

I'm pretty sure it was working correctly yesterday

**Update 1**: something to note is that `solc 0.8.15` as far as I know is already installed, so it should just directly compile without downloading and installing

**Update 2**: if I switch all the contracts to `pragma solidity 0.8.13;` it does compile. And it does not try to download+install solc 0.8.13. With `pragma solidity 0.8.15;` it tries to do so even if I should have already installed.

**Comment by RensR** [comment]
Experiencing the same issue, confirming everything works fine if I downgrade to `0.8.13`. I'm also on M1 and use 0.8.15. Worked perfectly until the latest `foundryup`.

**Comment by RensR** [comment]
Fixed by installing `z3` with `brew install z3`

**Comment by mattsse** [comment]
this could be related to the recent 0.8.16 we added.

could you please nuke the `~/.svm/*` folder, that's where we install all solc versions and try again?

**Comment by RensR** [comment]
Nuking the folder did not solve the issue. I found a more explicit error message

`Solc Error: dyld[60885]: Library not loaded: '/opt/homebrew/opt/z3/lib/libz3.dylib'
  Referenced from: '/Users/rens/.svm/0.8.15/solc-0.8.15'
  Reason: tried: '/opt/homebrew/opt/z3/lib/libz3.dylib' (no such file), '/usr/local/lib/libz3.dylib' (no such file), '/usr/lib/libz3.dylib' (no such file)
`

After installing `z3` everything works fine again.

**Comment by mattsse** [comment]
right, we now ship with z3 solver.
need to document this, thanks, on the book, https://github.com/foundry-rs/book/issues/515

closing this here

**Comment by StErMi** [comment]
@mattsse just to understand the solution if you are on **apple silicon**

- nuke the` ~/.svm/*` folder
- install `z3` from brew
- install solc

?

**Comment by mattsse** [comment]
first two points

nuke the ~/.svm/* folder
install z3 from brew

should be sufficient, since we handle installs directly via forge,

I think what probably happened here is that we recently added z3 to the apple silicon builds so checksums differ now

**Comment by StErMi** [comment]
ok, everything works like a charm!

**Comment by mattsse** [comment]
awesome, thanks for flagging, will add some troubleshooting docs for M1

**Comment by pagreczner** [comment]
I was on an M1 Pro with OS `11.x`  and was unable to resolve this issue with `z3` or `libusb` installs, compiling from source, or using the install script.

But, what finally worked was updating the OS entirely to `12.5.1` and was then able to successfully run `forge build` and `forge test`.

Leaving this note here in case this helps anyone else who comes here searching for a solution to the similar problem I had.

**Comment by VincentChenSupra** [comment]
I tried the steps and it does not work on my M1 Mac on Big Sur 11.6.2. Might have to try updating to 12+

**Comment by achiko** [comment]
> updating

I have also encountered the same problem on my M1 Big Sur 11.6, and I have already tried the same steps.

**Comment by ljrahn** [comment]
@achiko Im getting same error as you. deleting .svm, installing z3 and `npm i -g solc` did not work for me. Did you find a solution?

**Comment by vvlnko** [comment]
Folks. Could you please tell me how to downgrade foundry? I got macos

**Comment by kalloc** [comment]
`forge test --use $(which solc)` that may help you

**Comment by libaice** [comment]
I met this error because I used an 4G memory server, the memory is not enough to compile my all contracts, so, when I update a new 8G memory server, the problem is sloved ...

**Comment by intldds** [comment]
@ljrahn I'm getting the same error as you and @achiko -- `Solc Error: dyld: Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEEC1Ev Referenced from: ~/.svm/0.8.18/solc-0.8.18 (which was built for Mac OS X 13.0) Expected in: /usr/lib/libc++.1.dylib` -- were you able to solve it since April? I'm still running macOS 10.15.7 but I don't think that's the main reason for it to fail, any help would be much appreciated

**Comment by R-Morpheus** [comment]
hello guys, I have the same problem, but I have a macbook with an Intel chip, so the solutions above don't work for me. And updates to newer versions of the mac OS are not available to me

**Comment by unipooop** [comment]
My problem is like
[⠊] Compiling...
[⠘] Installing Solc version 0.8.24
[⠢] Successfully installed Solc 0.8.24
Error: 
solc exited with signal: 6 (SIGABRT)
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Expected in: /usr/lib/libc++.1.dylib
I'm new to here, how to deal with it

**Comment by TheWilsonGlobal** [comment]
It does work for 0.8.25 only with mac intel chip 
@R-Morpheus, @unipooop 
![Screen Shot 2024-08-09 at 08 18 17](https://github.com/user-attachments/assets/ed0e749d-fbfb-44fa-9783-0661385b54b5)

**Comment by finxlfantasy** [comment]
Did you get it fixed? I get the same exact error. It only works when I use _forge xyz --use 0.8.25_

I've tried changing the remote compiler to "v0.8.25+commit.b61c2a91", but still nothing is working. Also tried putting in specific version in foundry.toml - not working either.

**Comment by Huzaifa35756** [comment]
forge build
Error: error sending request for url (https://binaries.soliditylang.org/linux-amd64/list.json)

Context:
- Error #0: client error (Connect)
- Error #1: dns error: failed to lookup address information: Name or service not known

getting this error kindly guide
